[2021-12-16 07:38:30,393] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2021-12-16T07:38:15.017356+00:00 [queued]>
[2021-12-16 07:38:30,403] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user 2021-12-16T07:38:15.017356+00:00 [queued]>
[2021-12-16 07:38:30,411] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-16 07:38:30,411] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-16 07:38:30,412] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-16 07:38:30,430] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): processing_user> on 2021-12-16T07:38:15.017356+00:00
[2021-12-16 07:38:30,435] {standard_task_runner.py:52} INFO - Started process 38544 to run task
[2021-12-16 07:38:30,454] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'processing_user', '2021-12-16T07:38:15.017356+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpitfrt3qe', '--error-file', '/tmp/tmp4cds85yq']
[2021-12-16 07:38:30,455] {standard_task_runner.py:77} INFO - Job 18: Subtask processing_user
[2021-12-16 07:38:30,513] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.processing_user 2021-12-16T07:38:15.017356+00:00 [running]> on host airflowvm
[2021-12-16 07:38:30,595] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-12-16T07:38:15.017356+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-16T07:38:15.017356+00:00
[2021-12-16 07:38:30,615] {python.py:151} INFO - Done. Returned value was: None
[2021-12-16 07:38:30,619] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211216T073815, start_date=20211216T073830, end_date=20211216T073830
[2021-12-16 07:38:30,645] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-16 07:38:30,671] {local_task_job.py:151} INFO - Task exited with return code 0
