[2021-12-18 09:12:37,620] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-18T09:03:37.133567+00:00 [queued]>
[2021-12-18 09:12:37,625] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-18T09:03:37.133567+00:00 [queued]>
[2021-12-18 09:12:37,626] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:12:37,626] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-12-18 09:12:37,626] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:12:37,639] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): pull_from_git> on 2021-12-18T09:03:37.133567+00:00
[2021-12-18 09:12:37,641] {standard_task_runner.py:52} INFO - Started process 85475 to run task
[2021-12-18 09:12:37,647] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'pull_from_git', '2021-12-18T09:03:37.133567+00:00', '--job-id', '53', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmp0o43iidi', '--error-file', '/tmp/tmp8lgbw1mz']
[2021-12-18 09:12:37,648] {standard_task_runner.py:77} INFO - Job 53: Subtask pull_from_git
[2021-12-18 09:12:37,694] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.pull_from_git 2021-12-18T09:03:37.133567+00:00 [running]> on host airflowvm
[2021-12-18 09:12:37,852] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=pull_from_git
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T09:03:37.133567+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T09:03:37.133567+00:00
[2021-12-18 09:12:37,856] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 09:12:37,856] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/AlgorithmStudy_211124 pull']
[2021-12-18 09:12:37,867] {subprocess.py:75} INFO - Output:
[2021-12-18 09:12:38,251] {subprocess.py:79} INFO - Already up to date.
[2021-12-18 09:12:38,255] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 09:12:38,296] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=pull_from_git, execution_date=20211218T090337, start_date=20211218T091237, end_date=20211218T091238
[2021-12-18 09:12:38,364] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-18 09:12:38,388] {local_task_job.py:151} INFO - Task exited with return code 0
