[2021-12-18 09:03:19,252] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.cd_home 2021-12-18T08:50:25.202871+00:00 [queued]>
[2021-12-18 09:03:19,258] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.cd_home 2021-12-18T08:50:25.202871+00:00 [queued]>
[2021-12-18 09:03:19,259] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:03:19,259] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-18 09:03:19,259] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:03:19,272] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): cd_home> on 2021-12-18T08:50:25.202871+00:00
[2021-12-18 09:03:19,273] {standard_task_runner.py:52} INFO - Started process 83053 to run task
[2021-12-18 09:03:19,280] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'cd_home', '2021-12-18T08:50:25.202871+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmp4zx4nll4', '--error-file', '/tmp/tmp7zrpx11v']
[2021-12-18 09:03:19,280] {standard_task_runner.py:77} INFO - Job 44: Subtask cd_home
[2021-12-18 09:03:19,326] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.cd_home 2021-12-18T08:50:25.202871+00:00 [running]> on host airflowvm
[2021-12-18 09:03:19,451] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=cd_home
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T08:50:25.202871+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T08:50:25.202871+00:00
[2021-12-18 09:03:19,456] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 09:03:19,457] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /home/airflow']
[2021-12-18 09:03:19,472] {subprocess.py:75} INFO - Output:
[2021-12-18 09:03:19,474] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 09:03:19,498] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=cd_home, execution_date=20211218T085025, start_date=20211218T090319, end_date=20211218T090319
[2021-12-18 09:03:19,530] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-18 09:03:19,577] {local_task_job.py:151} INFO - Task exited with return code 0
