[2021-12-18 09:03:44,989] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.cd_home 2021-12-18T08:50:25.202871+00:00 [queued]>
[2021-12-18 09:03:45,001] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.cd_home 2021-12-18T08:50:25.202871+00:00 [queued]>
[2021-12-18 09:03:45,006] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:03:45,006] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-12-18 09:03:45,006] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:03:45,025] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): cd_home> on 2021-12-18T08:50:25.202871+00:00
[2021-12-18 09:03:45,027] {standard_task_runner.py:52} INFO - Started process 83342 to run task
[2021-12-18 09:03:45,040] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'cd_home', '2021-12-18T08:50:25.202871+00:00', '--job-id', '47', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpeq3t01sn', '--error-file', '/tmp/tmpgu11f1xt']
[2021-12-18 09:03:45,041] {standard_task_runner.py:77} INFO - Job 47: Subtask cd_home
[2021-12-18 09:03:45,142] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.cd_home 2021-12-18T08:50:25.202871+00:00 [running]> on host airflowvm
[2021-12-18 09:03:45,387] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=cd_home
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T08:50:25.202871+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T08:50:25.202871+00:00
[2021-12-18 09:03:45,394] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 09:03:45,395] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /home/airflow']
[2021-12-18 09:03:45,412] {subprocess.py:75} INFO - Output:
[2021-12-18 09:03:45,417] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 09:03:45,450] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=cd_home, execution_date=20211218T085025, start_date=20211218T090344, end_date=20211218T090345
[2021-12-18 09:03:45,503] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-18 09:03:45,534] {local_task_job.py:151} INFO - Task exited with return code 0
