[2021-12-18 09:38:53,037] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-18T09:38:49.639023+00:00 [queued]>
[2021-12-18 09:38:53,050] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-18T09:38:49.639023+00:00 [queued]>
[2021-12-18 09:38:53,055] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:38:53,055] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-18 09:38:53,056] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 09:38:53,082] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): pull_from_git> on 2021-12-18T09:38:49.639023+00:00
[2021-12-18 09:38:53,083] {standard_task_runner.py:52} INFO - Started process 90363 to run task
[2021-12-18 09:38:53,097] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'pull_from_git', '2021-12-18T09:38:49.639023+00:00', '--job-id', '74', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmp2g0iiark', '--error-file', '/tmp/tmp8frer9lw']
[2021-12-18 09:38:53,102] {standard_task_runner.py:77} INFO - Job 74: Subtask pull_from_git
[2021-12-18 09:38:53,175] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.pull_from_git 2021-12-18T09:38:49.639023+00:00 [running]> on host airflowvm
[2021-12-18 09:38:53,364] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=pull_from_git
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T09:38:49.639023+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T09:38:49.639023+00:00
[2021-12-18 09:38:53,365] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 09:38:53,367] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/AlgorithmStudy_211124 pull']
[2021-12-18 09:38:53,376] {subprocess.py:75} INFO - Output:
[2021-12-18 09:38:53,744] {subprocess.py:79} INFO - Already up to date.
[2021-12-18 09:38:53,745] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 09:38:53,771] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=pull_from_git, execution_date=20211218T093849, start_date=20211218T093853, end_date=20211218T093853
[2021-12-18 09:38:53,806] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-18 09:38:53,840] {local_task_job.py:151} INFO - Task exited with return code 0
