[2021-12-18 17:09:03,538] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-18T17:08:00+00:00 [queued]>
[2021-12-18 17:09:03,545] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.pull_from_git 2021-12-18T17:08:00+00:00 [queued]>
[2021-12-18 17:09:03,545] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 17:09:03,545] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-18 17:09:03,546] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 17:09:03,558] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): pull_from_git> on 2021-12-18T17:08:00+00:00
[2021-12-18 17:09:03,559] {standard_task_runner.py:52} INFO - Started process 13865 to run task
[2021-12-18 17:09:03,565] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'pull_from_git', '2021-12-18T17:08:00+00:00', '--job-id', '190', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpgajrmjwl', '--error-file', '/tmp/tmp6w08n60m']
[2021-12-18 17:09:03,566] {standard_task_runner.py:77} INFO - Job 190: Subtask pull_from_git
[2021-12-18 17:09:03,608] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.pull_from_git 2021-12-18T17:08:00+00:00 [running]> on host airflowvm
[2021-12-18 17:09:03,704] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=pull_from_git
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T17:08:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-18T17:08:00+00:00
[2021-12-18 17:09:03,705] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 17:09:03,705] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/AlgorithmStudy_211124 pull']
[2021-12-18 17:09:03,718] {subprocess.py:75} INFO - Output:
[2021-12-18 17:09:04,088] {subprocess.py:79} INFO - Already up to date.
[2021-12-18 17:09:04,094] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 17:09:04,120] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=pull_from_git, execution_date=20211218T170800, start_date=20211218T170903, end_date=20211218T170904
[2021-12-18 17:09:04,166] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-18 17:09:04,181] {local_task_job.py:151} INFO - Task exited with return code 0
