[2021-12-18 16:51:17,551] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [queued]>
[2021-12-18 16:51:17,556] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [queued]>
[2021-12-18 16:51:17,556] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 16:51:17,557] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-12-18 16:51:17,557] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 16:51:17,584] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): git_add> on 2021-12-18T16:09:43.600276+00:00
[2021-12-18 16:51:17,586] {standard_task_runner.py:52} INFO - Started process 8236 to run task
[2021-12-18 16:51:17,598] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'git_add', '2021-12-18T16:09:43.600276+00:00', '--job-id', '148', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpchynfyo8', '--error-file', '/tmp/tmpzew536qe']
[2021-12-18 16:51:17,599] {standard_task_runner.py:77} INFO - Job 148: Subtask git_add
[2021-12-18 16:51:17,662] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [running]> on host airflowvm
[2021-12-18 16:51:17,778] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=git_add
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T16:09:43.600276+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T16:09:43.600276+00:00
[2021-12-18 16:51:17,778] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 16:51:17,779] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/Test/ add rank.md']
[2021-12-18 16:51:17,784] {subprocess.py:75} INFO - Output:
[2021-12-18 16:51:17,788] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 16:51:17,806] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=git_add, execution_date=20211218T160943, start_date=20211218T165117, end_date=20211218T165117
[2021-12-18 16:51:17,833] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-18 16:51:17,845] {local_task_job.py:151} INFO - Task exited with return code 0
