[2021-12-18 16:54:13,726] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [queued]>
[2021-12-18 16:54:13,764] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [queued]>
[2021-12-18 16:54:13,773] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 16:54:13,777] {taskinstance.py:1068} INFO - Starting attempt 3 of 3
[2021-12-18 16:54:13,778] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 16:54:13,805] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): git_add> on 2021-12-18T16:09:43.600276+00:00
[2021-12-18 16:54:13,807] {standard_task_runner.py:52} INFO - Started process 8949 to run task
[2021-12-18 16:54:13,821] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'git_add', '2021-12-18T16:09:43.600276+00:00', '--job-id', '152', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmpgedod_vs', '--error-file', '/tmp/tmpifgwlfns']
[2021-12-18 16:54:13,826] {standard_task_runner.py:77} INFO - Job 152: Subtask git_add
[2021-12-18 16:54:13,925] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [running]> on host airflowvm
[2021-12-18 16:54:14,148] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=git_add
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T16:09:43.600276+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T16:09:43.600276+00:00
[2021-12-18 16:54:14,155] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 16:54:14,156] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/Test/ add rank.md']
[2021-12-18 16:54:14,162] {subprocess.py:75} INFO - Output:
[2021-12-18 16:54:14,168] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 16:54:14,206] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=git_add, execution_date=20211218T160943, start_date=20211218T165413, end_date=20211218T165414
[2021-12-18 16:54:14,256] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-18 16:54:14,277] {local_task_job.py:151} INFO - Task exited with return code 0
