[2021-12-18 16:55:37,306] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [queued]>
[2021-12-18 16:55:37,312] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [queued]>
[2021-12-18 16:55:37,312] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 16:55:37,313] {taskinstance.py:1068} INFO - Starting attempt 4 of 4
[2021-12-18 16:55:37,313] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-18 16:55:37,325] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): git_add> on 2021-12-18T16:09:43.600276+00:00
[2021-12-18 16:55:37,327] {standard_task_runner.py:52} INFO - Started process 9507 to run task
[2021-12-18 16:55:37,333] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'rank_update', 'git_add', '2021-12-18T16:09:43.600276+00:00', '--job-id', '157', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/rank_update.py', '--cfg-path', '/tmp/tmp2wfn58h5', '--error-file', '/tmp/tmp3e3h70a5']
[2021-12-18 16:55:37,333] {standard_task_runner.py:77} INFO - Job 157: Subtask git_add
[2021-12-18 16:55:37,370] {logging_mixin.py:104} INFO - Running <TaskInstance: rank_update.git_add 2021-12-18T16:09:43.600276+00:00 [running]> on host airflowvm
[2021-12-18 16:55:37,460] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=rank_update
AIRFLOW_CTX_TASK_ID=git_add
AIRFLOW_CTX_EXECUTION_DATE=2021-12-18T16:09:43.600276+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-18T16:09:43.600276+00:00
[2021-12-18 16:55:37,461] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-12-18 16:55:37,461] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'git -C /home/airflow/Test/ add rank.md']
[2021-12-18 16:55:37,465] {subprocess.py:75} INFO - Output:
[2021-12-18 16:55:37,467] {subprocess.py:83} INFO - Command exited with return code 0
[2021-12-18 16:55:37,485] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=rank_update, task_id=git_add, execution_date=20211218T160943, start_date=20211218T165537, end_date=20211218T165537
[2021-12-18 16:55:37,503] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-18 16:55:37,506] {local_task_job.py:151} INFO - Task exited with return code 0
